apiVersion: v1
kind: Pod
metadata:
  name: nginx-mysql-pod
  namespace: myapp
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
    - name: mysql-container
      image: mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
