apiVersion: v1
kind: Pod
metadata:
  name: ваш-pod
  namespace: namespace1
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
    - name: mysql-container
      image: mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ваш-secret
              key: root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: ваш-secret
              key: db-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ваш-secret
              key: db-password
        - name: MYSQL_DATABASE
          value: ваша-база-даних
